In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('datasets\\AQIDataIndia.csv')

In [4]:
df.head()

,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,Bihar,Kishanganj,"SDM Office_Khagra, Kishanganj - BSPCB",14-11-2025 21:00,26.088130,87.938403,NO2,NaN,NaN,NaN
1,Bihar,Kishanganj,"SDM Office_Khagra, Kishanganj - BSPCB",14-11-2025 21:00,26.088130,87.938403,CO,12.0,16.0,14.0
2,Bihar,Manguraha,"Forest Rest House, Manguraha - BSPCB",14-11-2025 21:00,27.308328,84.531742,PM2.5,45.0,117.0,61.0
3,Bihar,Manguraha,"Forest Rest House, Manguraha - BSPCB",14-11-2025 21:00,27.308328,84.531742,PM10,55.0,131.0,77.0
4,Bihar,Manguraha,"Forest Rest House, Manguraha - BSPCB",14-11-2025 21:00,27.308328,84.531742,NH3,1.0,2.0,1.0

In [5]:
df.shape

(3359, 10)

In [6]:
len(list(df.columns))

10

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3359 entries, 0 to 3358
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   state          3359 non-null   object
 1   city           3359 non-null   object
 2   station        3359 non-null   object
 3   last_update    3359 non-null   object
 4   latitude       3359 non-null   float64
 5   longitude      3359 non-null   float64
 6   pollutant_id   3359 non-null   object
 7   pollutant_min  3148 non-null   float64
 8   pollutant_max  3148 non-null   float64
 9   pollutant_avg  3148 non-null   float64
dtypes: float64(5), object(5)
memory usage: 262.6+ KB

In [8]:
df.isnull().sum()

state              0
city               0
station            0
last_update        0
latitude           0
longitude          0
pollutant_id       0
pollutant_min    211
pollutant_max    211
pollutant_avg    211
dtype: int64

In [9]:
df2 = df.dropna()

In [10]:
df.isnull().sum()

state              0
city               0
station            0
last_update        0
latitude           0
longitude          0
pollutant_id       0
pollutant_min    211
pollutant_max    211
pollutant_avg    211
dtype: int64

In [11]:
df2.isnull().sum()

state            0
city             0
station          0
last_update      0
latitude         0
longitude        0
pollutant_id     0
pollutant_min    0
pollutant_max    0
pollutant_avg    0
dtype: int64

In [12]:
df2.shape

(3148, 10)

In [13]:
import matplotlib.pyplot as plt

In [14]:
df['city'].where(df['state']=='Bihar')

0       Kishanganj
1       Kishanganj
2        Manguraha
3        Manguraha
4        Manguraha
           ...
3354           NaN
3355           NaN
3356           NaN
3357           NaN
3358           NaN
Name: city, Length: 3359, dtype: object

In [15]:
df['city'].where(df['state']=='Bihar')

0       Kishanganj
1       Kishanganj
2        Manguraha
3        Manguraha
4        Manguraha
           ...
3354           NaN
3355           NaN
3356           NaN
3357           NaN
3358           NaN
Name: city, Length: 3359, dtype: object

In [16]:
df['city'].where(df['state']=='Bihar').value_counts().dropna()

city
Patna           40
Gaya            19
Muzaffarpur     19
Bhagalpur       14
Munger           7
Kishanganj       7
Motihari         7
Manguraha        7
Bettiah          7
Chhapra          7
Buxar            7
Katihar          7
Araria           7
Arrah            7
Begusarai        7
Hajipur          7
Rajgir           7
Sasaram          7
Siwan            7
Aurangabad       7
Saharsa          7
Purnia           7
Bihar Sharif     6
Samastipur       6
Name: count, dtype: int64

In [17]:
df['city'].where(df['state']=='Bihar').dropna().value_counts()

city
Patna           40
Gaya            19
Muzaffarpur     19
Bhagalpur       14
Munger           7
Kishanganj       7
Motihari         7
Manguraha        7
Bettiah          7
Chhapra          7
Buxar            7
Katihar          7
Araria           7
Arrah            7
Begusarai        7
Hajipur          7
Rajgir           7
Sasaram          7
Siwan            7
Aurangabad       7
Saharsa          7
Purnia           7
Bihar Sharif     6
Samastipur       6
Name: count, dtype: int64

In [18]:
df.columns

Index(['state', 'city', 'station', 'last_update', 'latitude', 'longitude',
       'pollutant_id', 'pollutant_min', 'pollutant_max', 'pollutant_avg'],
      dtype='object')

In [19]:
df[['city','state','pollutant_max']].where(df['pollutant_max']>100).dropna()

           city          state  pollutant_max
2     Manguraha          Bihar          117.0
3     Manguraha          Bihar          131.0
12    Bhagalpur          Bihar          111.0
17        Buxar          Bihar          318.0
18        Buxar          Bihar          170.0
...         ...            ...            ...
3350    Kolkata    West_Bengal          259.0
3351    Kolkata    West_Bengal          118.0
3354   Siliguri    West_Bengal          130.0
3356   Siliguri    West_Bengal          105.0
3357  Vrindavan  Uttar_Pradesh          187.0

[1192 rows x 3 columns]

In [20]:
df[['city','pollutant_id','pollutant_max']].where(df.city=='Patna' and df.pollutant_max>100).dropna()

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
# df[['city','state','pollutant_id','pollutant_max']].where(df[(df['city'] == 'Patna') & (df['pollutant_max'] > 100)])

result = df[['city','state','pollutant_id','pollutant_max']].where(
    (df['city'] == 'Patna') & (df['pollutant_max'] > 100)
).dropna()

In [ ]:
result

       city  state pollutant_id  pollutant_max
68    Patna  Bihar         PM10          131.0
74    Patna  Bihar           CO          103.0
88    Patna  Bihar         PM10          166.0
720   Patna  Bihar         PM10          148.0
1424  Patna  Bihar          NO2          101.0
1425  Patna  Bihar           CO          114.0
2096  Patna  Bihar        PM2.5          277.0
2097  Patna  Bihar        PM2.5          185.0
2098  Patna  Bihar          NO2          294.0
2099  Patna  Bihar        PM2.5          428.0
2743  Patna  Bihar        PM2.5          216.0
2744  Patna  Bihar         PM10          301.0
2768  Patna  Bihar           CO          111.0
2769  Patna  Bihar        PM2.5          307.0
2771  Patna  Bihar           CO          106.0
2786  Patna  Bihar        OZONE          219.0

In [ ]:
df[['city','state','pollutant_max']].where(df['pollutant_max']>100).dropna()

           city          state  pollutant_max
2     Manguraha          Bihar          117.0
3     Manguraha          Bihar          131.0
12    Bhagalpur          Bihar          111.0
17        Buxar          Bihar          318.0
18        Buxar          Bihar          170.0
...         ...            ...            ...
3350    Kolkata    West_Bengal          259.0
3351    Kolkata    West_Bengal          118.0
3354   Siliguri    West_Bengal          130.0
3356   Siliguri    West_Bengal          105.0
3357  Vrindavan  Uttar_Pradesh          187.0

[1192 rows x 3 columns]

In [ ]:
result

,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
68,Bihar,Patna,"Muradpur, Patna - BSPCB",14-11-2025 21:00,25.619651,85.147382,PM10,113.0,131.0,120.0
74,Bihar,Patna,"Samanpura, Patna - BSPCB",14-11-2025 21:00,25.596727,85.085624,CO,2.0,103.0,65.0
88,Bihar,Patna,"Govt. High School Shikarpur, Patna - BSPCB",14-11-2025 21:00,25.592539,85.227158,PM10,103.0,166.0,133.0
720,Bihar,Patna,"Rajbansi Nagar, Patna - BSPCB",14-11-2025 21:00,25.599486,85.113666,PM10,80.0,148.0,116.0
1424,Bihar,Patna,"DRM Office Danapur, Patna - BSPCB",14-11-2025 21:00,25.586562,85.043586,NO2,37.0,101.0,63.0
1425,Bihar,Patna,"DRM Office Danapur, Patna - BSPCB",14-11-2025 21:00,25.586562,85.043586,CO,32.0,114.0,64.0
2096,Bihar,Patna,"Muradpur, Patna - BSPCB",14-11-2025 21:00,25.619651,85.147382,PM2.5,76.0,277.0,198.0
2097,Bihar,Patna,"Rajbansi Nagar, Patna - BSPCB",14-11-2025 21:00,25.599486,85.113666,PM2.5,68.0,185.0,120.0
2098,Bihar,Patna,"Rajbansi Nagar, Patna - BSPCB",14-11-2025 21:00,25.599486,85.113666,NO2,66.0,294.0,134.0
2099,Bihar,Patna,"Samanpura, Patna - BSPCB",14-11-2025 21:00,25.596727,85.085624,PM2.5,92.0,428.0,338.0
2743,Bihar,Patna,"DRM Office Danapur, Patna - BSPCB",14-11-2025 21:00,25.586562,85.043586,PM2.5,85.0,216.0,147.0
2744,Bihar,Patna,"DRM Office Danapur, Patna - BSPCB",14-11-2025 21:00,25.586562,85.043586,PM10,81.0,301.0,138.0
2768,Bihar,Patna,"Govt. High School Shikarpur, Patna - BSPCB",14-11-2025 21:00,25.592539,85.227158,CO,54.0,111.0,77.0
2769,Bihar,Patna,"IGSC Planetarium Complex, Patna - BSPCB",14-11-2025 21:00,25.610369,85.132568,PM2.5,79.0,307.0,207.0
2771,Bihar,Patna,"Rajbansi Nagar, Patna - BSPCB",14-11-2025 21:00,25.599486,85.113666,CO,24.0,106.0,64.0
2786,Bihar,Patna,"Samanpura, Patna - BSPCB",14-11-2025 21:00,25.596727,85.085624,OZONE,6.0,219.0,93.0

In [21]:
df.head()

,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,Bihar,Kishanganj,"SDM Office_Khagra, Kishanganj - BSPCB",14-11-2025 21:00,26.088130,87.938403,NO2,NaN,NaN,NaN
1,Bihar,Kishanganj,"SDM Office_Khagra, Kishanganj - BSPCB",14-11-2025 21:00,26.088130,87.938403,CO,12.0,16.0,14.0
2,Bihar,Manguraha,"Forest Rest House, Manguraha - BSPCB",14-11-2025 21:00,27.308328,84.531742,PM2.5,45.0,117.0,61.0
3,Bihar,Manguraha,"Forest Rest House, Manguraha - BSPCB",14-11-2025 21:00,27.308328,84.531742,PM10,55.0,131.0,77.0
4,Bihar,Manguraha,"Forest Rest House, Manguraha - BSPCB",14-11-2025 21:00,27.308328,84.531742,NH3,1.0,2.0,1.0

In [23]:
df['last_update'] = pd.to_datetime(df['last_update'])

C:\Users\Hp\AppData\Local\Temp\ipykernel_8536\835296419.py:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['last_update'] = pd.to_datetime(df['last_update'])

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3359 entries, 0 to 3358
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   state          3359 non-null   object
 1   city           3359 non-null   object
 2   station        3359 non-null   object
 3   last_update    3359 non-null   datetime64[ns]
 4   latitude       3359 non-null   float64
 5   longitude      3359 non-null   float64
 6   pollutant_id   3359 non-null   object
 7   pollutant_min  3148 non-null   float64
 8   pollutant_max  3148 non-null   float64
 9   pollutant_avg  3148 non-null   float64
dtypes: datetime64[ns](1), float64(5), object(4)
memory usage: 262.6+ KB

In [25]:
df['last_update'].dt.date

0       2025-11-14
1       2025-11-14
2       2025-11-14
3       2025-11-14
4       2025-11-14
           ...
3354    2025-11-14
3355    2025-11-14
3356    2025-11-14
3357    2025-11-14
3358    2025-11-14
Name: last_update, Length: 3359, dtype: object

In [26]:
df['last_update'].dt.time

0       21:00:00
1       21:00:00
2       21:00:00
3       21:00:00
4       21:00:00
          ...
3354    21:00:00
3355    21:00:00
3356    21:00:00
3357    21:00:00
3358    21:00:00
Name: last_update, Length: 3359, dtype: object

In [27]:
df.describe()

,last_update,latitude,longitude,pollutant_min,pollutant_max,pollutant_avg
count,3359,3359.000000,3359.000000,3148.000000,3148.000000,3148.000000
mean,2025-11-14 21:00:00,22.676211,78.581460,36.598158,105.235070,66.389454
min,2025-11-14 21:00:00,8.514909,70.909168,1.000000,1.000000,1.000000
25%,2025-11-14 21:00:00,19.061749,75.555917,5.750000,19.000000,13.000000
50%,2025-11-14 21:00:00,23.243639,77.310100,16.000000,64.500000,38.000000
75%,2025-11-14 21:00:00,27.198658,80.327067,46.000000,141.000000,88.250000
max,2025-11-14 21:00:00,34.066206,94.636574,352.000000,500.000000,432.000000
std,NaN,5.522318,4.847776,54.161807,116.504759,79.052099